<?php echo $this->form()->openTag($form); ?>
<div class="form_element">
    <?php echo $this->formRow($form->get('usuario')); ?>
</div>

<div class="form_element">
    <?php echo $this->formRow($form->get('senha')); ?>
</div>


<?php if ($form->has('id')): ?>
    <?php echo $this->formElement($form->get('id')) ?>
<?php endif;?>

<?php echo $this->formElement($form->get('send')) ?>

<?php echo $this->form()->closeTag() ?>
